#pragma once

#define INITIAL_GLFW_WINDOW_WIDTH 800
#define INITIAL_GLFW_WINDOW_HEIGHT 800
#define INITIAL_OPENGL_CONTEXT_SCREEN_WIDTH 800
#define INITIAL_OPENGL_CONTEXT_SCREEN_HEIGHT 640

#define INITIAL_ASPECT_RATIO 1.25f

#define CAMERA_INITIAL_POS_X 1.0f
#define CAMERA_INITIAL_POS_Y 1.0f
#define CAMERA_INITIAL_POS_Z 1.0f
#define CAMERA_INITIAL_FRONT_X 0.0f
#define CAMERA_INITIAL_FRONT_Y -0.3f
#define CAMERA_INITIAL_FRONT_Z -1.0f
#define CAMERA_TRANSLATION_SENSITIVITY 10.0f
#define CAMERA_SCROLL_SENSITIVITY 10.0f

#define CAMERA_SPEED 3.0f
#define MOUSE_SENSITIVITY 0.06f
#define INITIAL_YAW -90.0f
#define INITIAL_PITCH -45.0f
#define INITIAL_ZOOM 45.0f