#pragma once

#define INITIAL_GLFW_WINDOW_WIDTH 1280
#define INITIAL_GLFW_WINDOW_HEIGHT 720
#define INITIAL_GLFW_WINDOW_POSITION_X 300
#define INITIAL_GLFW_WINDOW_POSITION_Y 300
#define INITIAL_OPENGL_CONTEXT_SCREEN_WIDTH 800
#define INITIAL_OPENGL_CONTEXT_SCREEN_HEIGHT 640
#define INITIAL_OPENGL_CONTEXT_POSITION_X 256
#define INITIAL_OPENGL_CONTEXT_POSITION_Y 83
#define FULL_SCREEN_SIZE_X 1920
#define FULL_SCREEN_SIZE_Y 1080

#define INITIAL_ASPECT_RATIO 1.25f

#define CAMERA_INITIAL_POS_X 1.0f
#define CAMERA_INITIAL_POS_Y 1.0f
#define CAMERA_INITIAL_POS_Z 1.0f
#define CAMERA_INITIAL_FRONT_X 0.0f
#define CAMERA_INITIAL_FRONT_Y -0.3f
#define CAMERA_INITIAL_FRONT_Z -1.0f
#define CAMERA_TRANSLATION_SENSITIVITY 10.0f
#define CAMERA_SCROLL_SENSITIVITY 10.0f

#define CAMERA_SPEED 3.0f
#define CAMERA_MAX_SPEED 10.0f
#define MOUSE_SENSITIVITY 0.06f
#define INITIAL_YAW -90.0f
#define INITIAL_PITCH -45.0f
#define INITIAL_ZOOM 45.0f

#define SELECTING_OBJECT_RANGE 30.0f
#define SELECTING_OBJECT_PRECISION 0.005f

#define INITIAL_NEAR_PLANE_VALUE 0.1f
#define INITIAL_FAR_PLANE_VALUE 100.0f

#define MODIFYING_VECTORS_INITIAL_SIZE 1.0f
#define MODIFYING_VECTORS_ARROW_LENGTH .15f
#define MODIFYING_VECTORS_ARROW_ANGLE 8.0f
#define MODIFYING_VECTORS_ARROW_CIRCLE_INTERVAL 45.0f
