#pragma once

#define INITIAL_GLFW_WINDOW_WIDTH 1280
#define INITIAL_GLFW_WINDOW_HEIGHT 720
#define INITIAL_GLFW_WINDOW_POSITION_X 300
#define INITIAL_GLFW_WINDOW_POSITION_Y 300
#define INITIAL_OPENGL_CONTEXT_SCREEN_WIDTH 800
#define INITIAL_OPENGL_CONTEXT_SCREEN_HEIGHT 640
#define INITIAL_OPENGL_CONTEXT_POSITION_X 256
#define INITIAL_OPENGL_CONTEXT_POSITION_Y 83
#define FULL_SCREEN_SIZE_X 1920
#define FULL_SCREEN_SIZE_Y 1080

#define INITIAL_ASPECT_RATIO 1.25f

#define CAMERA_INITIAL_POS_X 1.0f
#define CAMERA_INITIAL_POS_Y 1.0f
#define CAMERA_INITIAL_POS_Z 1.0f
#define CAMERA_INITIAL_FRONT_X 0.0f
#define CAMERA_INITIAL_FRONT_Y -0.3f
#define CAMERA_INITIAL_FRONT_Z -1.0f
#define CAMERA_TRANSLATION_SENSITIVITY 10.0f
#define CAMERA_SCROLL_SENSITIVITY 10.0f

#define CAMERA_SPEED 3.0f
#define CAMERA_MAX_SPEED 10.0f
#define MOUSE_SENSITIVITY 0.06f
#define INITIAL_YAW -90.0f
#define INITIAL_PITCH -45.0f
#define INITIAL_ZOOM 45.0f

#define SELECTING_OBJECT_RANGE 30.0f
#define SELECTING_OBJECT_PRECISION 0.005f

#define RAY_LENGTH 20.0f

#define INITIAL_NEAR_PLANE_VALUE 0.1f
#define INITIAL_FAR_PLANE_VALUE 100.0f

#define MODIFYING_VECTORS_INITIAL_SIZE 1.0f
#define MODIFYING_VECTORS_ARROW_LENGTH .15f
#define MODIFYING_VECTORS_ARROW_ANGLE 8.0f
#define MODIFYING_VECTORS_ARROW_CIRCLE_INTERVAL 22.5f
#define MODIFYING_VECTORS_BOUNDARY_HALF_SIZE .03f
#define MODIFYING_VECTORS_MOVEMENT_STEP .01f
#define MODIFYING_VECTORS_ROTATION_CIRCLE_SEGMENT_NUM 30
#define MODIFYING_VECTORS_ROTATION_CIRCLE_ANGLE_SEPARATION 10.0f
#define MODIFYING_VECTORS_ROTATION_BOUNDARY_DISTANCE_CHECK .05f

#define MIN_OBJECT_SIZE .01f
#define MAX_OBJECT_SIZE 200.0f
#define MAX_DISTANCE_RESIZE_JUMP 160.0f

#define CYLINDER_DRAWING_ANGLE_INTERVAL 11.25f
#define CYLINDER_BOUNDARY_DETECTION_PRECISION 45.0f

#define MAX_NUM_PADS 50
#define MIN_NUM_PADS 1
#define MIN_PAD_SEPARATION_SIZE .01f
#define MAX_PAD_SEPARATION_SIZE 3

#define CIRCUMFERENCE 360.0f

#define DIMENSIONAL_CURVE_DELTA_LENGTH .015f
#define DIMENSIONAL_CURVE_DIAMETER .02f
#define DIMENSIONAL_CURVE_CIRCLE_NUM_SEGMENTS 16
#define CURVE_CHECK_HIGHER_POINT_OBJ_MARGIN .01
#define WIRE_MIN_DIAMETER .005
#define WIRE_MAX_DIAMETER .05

#define RIBBON_DEFAULT_INITIAL_Y 0.0f
#define RIBBON_DEFAULT_FINAL_Y 0.0f
#define RIBBON_DEFAULT_TAIL_SIZE 0.1f
#define RIBBON_DEFAULT_CURVE_HEIGHT 0.05f
#define RIBBON_INITIAL_WIDTH .15f
//#define RIBBON_INITIAL_HEIGHT .02f
#define RIBBON_INITIAL_THICKNESS .02f
#define RIBBON_NUM_SEGMENTS 40
#define RIBBON_BOUNDARY_CHECK_FEET_NUM 40

#define RIBBON_MAX_CURVE_HEIGHT .15f
#define RIBBON_MAX_CURVE_TAIL .3f
#define RIBBON_MAX_CURVE_WIDTH 1.0f
#define RIBBON_MAX_CURVE_THICKNESS .1f
#define RIBBON_MIN_CURVE_HEIGHT .02f
#define RIBBON_MIN_CURVE_TAIL .02f
#define RIBBON_MIN_CURVE_WIDTH .02f
#define RIBBON_MIN_CURVE_THICKNESS .01f

#define MAX_COORD_VALUE 10000.0
#define MIN_COORD_VALUE -10000.0

#define EPSILON 1e-6f

#define SIMULATION_INITIAL_CELL_SIZE .1f

#define SPEED_OF_LIGHT 299792458.0
#define GHZ_TO_HZ 1000000000

#define POWER_SOURCE_INITIAL_FREQUENCY 4.0